package htbgo

// Get a list of universities
type Universities struct {
	Message string `json:"message"`
	Section string `json:"section"`
	Data    struct {
		University []struct {
			ID                   int      `json:"id"`
			Name                 string   `json:"name"`
			HasAutoGeneratedLogo int      `json:"has_auto_generated_logo"`
			CCA2                 string   `json:"cca2"`
			CreatedAt            string   `json:"created_at"`
			UsersCount           int      `json:"users_count"`
			RespectedByCount     int      `json:"respected_by_count"`
			Country              string   `json:"country"`
			UsersAvatartThumb    []string `json:"user_avatars"`
		} `json:"data"`
		NextPage     string `json:"next_page_url"`
		Path         string `json:"path"`
		PerPage      int    `json:"per_page"`
		PreviousPage string `json:"prev_page_url"`
		to           int    `json:"to"`
		Total        int    `json:"total"`
	}
}

// will fix the query later
func (s *Session) Universities(page string, query string) (universities Universities) {
	if page == "" {
		page = "1"
	}
	var url string = "https://www.hackthebox.com/api/v4/university/all/list?page=" + page + "&search=" + query
	parseJSON(s, url, &universities)

	return
}
